import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import Hero from "@/components/Hero/Hero";
import LocationDesc from "@/components/LocationDescription/LocationDesc";
import Amenities from "@/components/Amenities/Amenities";
import BestRated from "@/components/BestRated/BestRated";
import Discover from "@/components/Discover/Discover";
import Explore from "@/components/Explore/Explore";
import BestDeals from "@/components/BestDeals/BestDeals";
import PerfectPlace from "@/components/PerfectPlace/PerfectPlace";
import Features from "@/components/Features/Features";
import Pricing from "@/components/Pricing/Pricing";
import FAQ from "@/components/FAQ/FAQ";
import FAQRatings from "@/components/FAQRatings/FAQRatings";
import ContactUs from "@/components/ContactUs/ContactUs";
import StayUpdated from "@/components/StayUpdated/StayUpdated";
import Instagram from "@/components/Instagram/Instagram";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MyRental</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Hero />
        <LocationDesc />
        <Amenities />
        <BestRated />
        <Discover />
        <Explore />
        <BestDeals />
        <PerfectPlace />
        <Features />
        <Pricing />
        <FAQ />
        <FAQRatings />
        <ContactUs />
        <StayUpdated />
        <Instagram />
        <Footer />
      </main>
    </>
  );
}
